model_list:
  - model_name: haru:canonical
    litellm_params:
      model: bedrock_mantle/google.gemma-4-26b-a4b
      api_key: os.environ/BEDROCK_MANTLE_API_KEY
      temperature: 1.0
      top_p: 0.95

litellm_settings:
  drop_params: true
  callbacks: [litellm_post_fix.proxy_handler_instance]
