<?xml version="1.0"?><package format="3"><name>haru_recording_bringup</name><version>0.1.0</version><description>Isolated Recorder and Viz integration launches</description><maintainer email="levko@livanchuk.com">Levko Ivanchuk</maintainer><license>Proprietary</license><buildtool_depend>ament_cmake</buildtool_depend><buildtool_depend>ament_cmake_python</buildtool_depend><exec_depend>haru_recorder</exec_depend><exec_depend>strawberry_resource_monitor</exec_depend><exec_depend>haru_viz</exec_depend><exec_depend>launch_ros</exec_depend><exec_depend>ament_index_python</exec_depend><exec_depend>rclpy</exec_depend><exec_depend>rosbag2_py</exec_depend><exec_depend>std_msgs</exec_depend><exec_depend>domain_bridge</exec_depend><exec_depend>tf2_msgs</exec_depend><exec_depend>sensor_msgs</exec_depend><export><build_type>ament_cmake</build_type></export>  <test_depend>ament_cmake_pytest</test_depend>
</package>
