model_list:

  - model_name: gpt-5-mini
    litellm_params:
      model: openai/gpt-5-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-4.1-mini
    litellm_params:
      model: openai/gpt-4.1-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: claude-sonnet-4-0
    litellm_params:
      model: anthropic/claude-sonnet-4-0
      api_key: os.environ/ANTHROPIC_API_KEY
  
  - model_name: llama-3.1-70b
    litellm_params:
      model: hosted_vllm/hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4
      api_base: http://dgx02:8001/v1
  
  - model_name: llama-3.1-8b
    litellm_params:
      model: hosted_vllm/hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4
      api_base: http://dgx02:8002/v1

  - model_name: gpt-oss-120b
    litellm_params:
      model: hosted_vllm/openai/gpt-oss-120b
      api_base: http://dgx02:8004/v1
