name: haru-common

services:
  common-service:
    image: scratch
    init: true
    restart: unless-stopped

  common-ros:
    image: scratch
    extends:
      service: common-service
    environment:
      ROS_DOMAIN_ID: ${HARU_ROBOT_ROS_DOMAIN_ID:-${ROS_DOMAIN_ID:-0}}
    network_mode: host
    ipc: host
    stop_grace_period: 10s

  common-gpu:
    image: scratch
    extends:
      service: common-service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  common-ros-gpu:
    image: scratch
    extends:
      service: common-ros
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
