name: haru-speech

services:
  download-models:
    image: ghcr.io/haru-project/haru-speech:ros2
    working_dir: /ros2_ws/src/haru-speech
    command: ["/bin/bash", "-c", "/root/.local/bin/uv pip install --python $PACKAGE_VENV --upgrade pip && $PACKAGE_VENV -m haru_speech.models.download"]
    env_file: ../envs/speech.env
    volumes:
      - ~/haru-speech-cache/models:${HARU_SPEECH_MODELS_DIR}:rw
    profiles: ["setup"]
  
  clear-models:
    image: ghcr.io/haru-project/haru-speech:ros2
    working_dir: /ros2_ws/src/haru-speech
    command: ["/bin/bash", "-c", "/root/.local/bin/uv pip install --python $PACKAGE_VENV --upgrade pip && $PACKAGE_VENV -m haru_speech.models.clear"]
    env_file: ../envs/speech.env
    volumes:
      - ~/haru-speech-cache/models:${HARU_SPEECH_MODELS_DIR}:rw
    profiles: ["setup"]

  audio:
    extends:
      file: compose.common.yaml
      service: common-ros
    image: ghcr.io/haru-project/haru-speech:ros2
    command: [
      "ros2", "launch", "haru_speech_ros", "audio.launch.py",
      "config_file:=${AUDIO_CONFIG_FILE}",
      "dev_autostart:=true",
    ]
    env_file: ../envs/speech.env
    devices:
      - /dev/snd
    volumes:
      - ../data/speech/configs:/shared/configs:rw
    restart: unless-stopped

  configure:
    extends:
      file: compose.common.yaml
      service: common-ros
    image: ghcr.io/haru-project/haru-speech:ros2
    command: [
      "ros2", "launch", "haru_speech_ros", "configure.launch.py",
      "config_file:=${AUDIO_CONFIGURE_CONFIG_FILE}",
      "dev_autostart:=true",
    ]
    env_file: ../envs/speech.env
    volumes:
      - ../data/speech/configs:/shared/configs:rw
    restart: unless-stopped
  
  recognition:
    extends:
      file: compose.common.yaml
      service: common-ros-gpu
    image: ghcr.io/haru-project/haru-speech:ros2
    command: [
      "ros2", "launch", "haru_speech_ros", "speech_to_text.launch.py",
      "config_file:=${SPEECH_RECOGNITION_CONFIG_FILE}",
      "dev_autostart:=true",
    ]
    env_file: ../envs/speech.env
    volumes:
      - ../data/speech/configs:/shared/configs:rw
      - ~/haru-speech-cache/models:${HARU_SPEECH_MODELS_DIR}:rw
    restart: unless-stopped
    
  verification:
    extends:
      file: compose.common.yaml
      service: common-ros-gpu
    image: ghcr.io/haru-project/haru-speech:ros2
    command: [
      "ros2", "launch", "haru_speech_ros", "speaker_verification.launch.py",
      "config_file:=${SPEAKER_VERIFICATION_CONFIG_FILE}",
      "dev_autostart:=true",
    ]
    env_file: ../envs/speech.env
    volumes:
      - ../data/speech/configs:/shared/configs:rw
      - ~/haru-speech-cache/models:${HARU_SPEECH_MODELS_DIR}:rw
      - ~/haru-speech-cache/voices:${HARU_SPEECH_VOICES_DIR}:rw
    restart: unless-stopped
    
  localization:
    extends:
      file: compose.common.yaml
      service: common-ros-gpu
    image: ghcr.io/haru-project/haru-speech:ros2
    command: [
      "ros2", "launch", "haru_speech_ros", "sound_localization.launch.py",
      "config_file:=${SOUND_LOCALIZATION_CONFIG_FILE}",
    ]
    env_file: ../envs/speech.env
    volumes:
      - ../data/speech/configs:/shared/configs:rw
      - ~/haru-speech-cache/models:${HARU_SPEECH_MODELS_DIR}:rw
    restart: unless-stopped
