name: haru-simulator

services:
  unity-app:
    image: ghcr.io/haru-project/haru-simulator:ros2-fastdds
    command: ["/bin/bash", "-c", "export ROS_IP=$(hostname -I | awk '{print $1}') && ros2 launch haru_unity unity_app_launcher_launch.py && tail -f /dev/null"]
    env_file: ../envs/simulator.env
    network_mode: host
    ipc: host
    devices:
      - /dev/snd
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  
  web-server:
    image: ghcr.io/haru-project/haru-simulator:ros2-fastdds
    working_dir: /app/haru2_web/
    command: ["/bin/bash", "-c", "cd haru_web && \
      ../.venv/bin/python3 -m streamlit run Home.py \
        --server.port 7000 \
        --server.address 0.0.0.0 \
        --server.headless true \
        --server.baseUrlPath '/haru_web'",
    ]
    env_file: ../envs/simulator.env
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix