name: haru-simulator

services:
  unity-app:
    extends:
      file: compose.common.yaml
      service: common-ros-gpu
    image: ghcr.io/haru-project/hve-simulator:feature-ci
    command: ["/bin/bash", "-c", "export ROS_IP=$(hostname -I | awk '{print $1}') && ros2 launch haru_unity unity_app_launcher_launch.py && tail -f /dev/null"]
    env_file: ../envs/simulator.env
    devices:
      - /dev/snd
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../data/simulator/resources:/ros2_ws/src/haru2_core/resources:rw
      - ../data/simulator/playerprefs:/root/.config/unity3d/Miraitec/HaruVirtualEnvironments:rw

  web-server:
    extends:
      file: compose.common.yaml
      service: common-service
    image: ghcr.io/haru-project/hve-simulator:feature-ci
    working_dir: /app/haru2_web/
    command: ["/bin/bash", "-c", "bash run_web.sh"]
    env_file: ../envs/simulator.env
    ports:
      - 7000:7000
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../data/simulator/resources:/ros2_ws/src/haru2_core/resources:rw
