name: haru-projector

services:

  server:
    extends:
      file: compose.common.yaml
      service: common-ros
    image: ${HARU_PROJECTOR_IMAGE:-ghcr.io/haru-project/haru-web-projector@sha256:e07fe2cbfb105a47227fc1ad790227aaf87ad0cfd676051180c0afc95e640c69}
    env_file: ../envs/projector.env
    environment:
      HARU_PARAM__DEV_AUTOSTART: "true"
      HARU_PARAM__WEB_SERVER_PORT: "${PROJECTOR_HOST_PORT:-8081}"
    volumes:
      - ../data/reasoner/projector:/shared/projector/resources:ro
      - ../data/session/:/root/.bt_ros:ro
    restart: unless-stopped
