name: haru-projector

services:

  server:
    extends:
      file: compose.common.yaml
      service: common-ros
    image: ghcr.io/haru-project/haru-web-projector:latest
    env_file: ../envs/projector.env
    environment:
      HARU_PARAM__DEV_AUTOSTART: "true"
      HARU_PARAM__WEB_SERVER_PORT: "8081"
    volumes:
      - ../data/reasoner/projector:/shared/projector/resources:ro
      - ../data/session/:/root/.bt_ros:ro
    restart: unless-stopped
