"""Generate ignored host-local configuration without changing tracked defaults."""

from __future__ import annotations

import json
import os
from pathlib import Path
import stat
from typing import Any

from dotenv import dotenv_values
from ruamel.yaml import YAML

from .models import AGENT_MODEL_KEYS, Deployment, LLMProvider, SetupAnswers


STACK_FILES = {
    "domain-bridge": "docker-compose-domain-bridge.yaml",
    "perception": "docker-compose-perception.yaml",
    "speech": "docker-compose-speech.yaml",
    "llm": "docker-compose-llm.yaml",
    "reasoner": "docker-compose-reasoner.yaml",
    "tts": "docker-compose-tts.yaml",
    "simulator": "docker-compose-simulator.yaml",
    "ipad": "docker-compose-ipad.yaml",
    "projector": "docker-compose-projector.yaml",
    "user": "docker-compose-user.yaml",
    "nlp": "docker-compose-nlp.yaml",
    "timeline-player": "docker-compose-timeline-player.yaml",
    "memory": "docker-compose-memory.yaml",
    "all": "docker-compose-all.yaml",
}


class ConfigurationWriter:
    def __init__(self, root: Path) -> None:
        self.root = root.resolve()
        self.local_dir = self.root / ".haru"
        self.yaml = YAML()
        self.yaml.default_flow_style = False

    def write(self, answers: SetupAnswers, secret: str | None = None) -> None:
        self.local_dir.mkdir(parents=True, exist_ok=True)
        self._write_answers(answers)
        self._write_local_env(answers)
        self._write_compose_overrides(answers)
        self._write_speech_config(answers)
        if secret:
            self._write_secret(answers.secret_name, secret)
        if answers.llm_provider == LLMProvider.CUSTOM:
            self._write_custom_litellm(answers)

    def _write_answers(self, answers: SetupAnswers) -> None:
        path = self.local_dir / "answers.yaml"
        with path.open("w", encoding="utf-8") as stream:
            self.yaml.dump(answers.model_dump(mode="json"), stream)

    def _write_local_env(self, answers: SetupAnswers) -> None:
        values: dict[str, str] = {
            "ROS_DOMAIN_ID": str(answers.robot_domain_id),
            "HARU_ROBOT_ROS_DOMAIN_ID": str(answers.robot_domain_id),
            "HARU_PERCEPTION_ROS_DOMAIN_ID": str(answers.perception_domain_id),
            "FROM_DOMAIN_ID": str(answers.perception_domain_id),
            "TO_DOMAIN_ID": str(answers.robot_domain_id),
            "HARU_VIZ_UI_PORT": str(answers.viz_port),
            "HARU_ROSBRIDGE_PORT": str(answers.rosbridge_port),
            "HARU_ROSBRIDGE_RGB_PORT": str(answers.rosbridge_port + 1),
            "HARU_ROSBRIDGE_DEPTH_PORT": str(answers.rosbridge_port + 2),
            "HARU_ROSBRIDGE_DEPTH_TO_RGB_PORT": str(answers.rosbridge_port + 3),
            "LLM_SERVER_HOST_PORT": str(answers.llm_port),
            "LLM_SERVER_BASE_URL": f"http://127.0.0.1:{answers.llm_port}",
            "GROOT_MONITOR_ENABLED": str(answers.groot_enabled).lower(),
            "HARU_DEPLOYMENT": answers.deployment.value,
            "HARU_ROBOT_HOST": answers.robot_host or "",
            "HARU_GPU_AVAILABLE": str(answers.gpu_available).lower(),
            "HARU_NLP_SERVER_GPU_ENABLED": str(answers.gpu_available).lower(),
        }
        values.update({key: answers.llm_model_id for key in AGENT_MODEL_KEYS})
        path = self.local_dir / "local.env"
        path.write_text(
            "# Generated by haru-local. Re-run setup instead of editing.\n"
            + "".join(f"{key}={value}\n" for key, value in values.items()),
            encoding="utf-8",
        )

    def _write_compose_overrides(self, answers: SetupAnswers) -> None:
        local_env = str(self.local_dir / "local.env")
        behavior_dir = self.root / "config" / "behavior_trees"
        for stack, filename in STACK_FILES.items():
            source = self.root / "apps" / filename
            if not source.exists():
                continue
            with source.open(encoding="utf-8") as stream:
                compose = self.yaml.load(stream) or {}
            services = compose.get("services", {})
            override: dict[str, Any] = {
                "services": {
                    name: {"env_file": [{"path": local_env, "required": True}]}
                    for name in services
                }
            }
            if stack in {"reasoner", "all"} and answers.deployment == Deployment.PHYSICAL:
                service_name = "bt-forest"
                if service_name in override["services"]:
                    override["services"][service_name]["volumes"] = [
                        (
                            f"{behavior_dir / 'simple_gaze_controller.xml'}:"
                            "/opt/ros/jazzy/workspace/install/share/behavior_tree_strawberry/"
                            "bt_palettes/simple_gaze_controller.xml:ro"
                        ),
                    ]
            path = self.local_dir / f"compose-{stack}.yaml"
            with path.open("w", encoding="utf-8") as stream:
                self.yaml.dump(override, stream)

    def _write_speech_config(self, answers: SetupAnswers) -> None:
        source_path = self.root / "data" / "speech" / "configs" / "haru_speech.yaml"
        if not source_path.exists():
            return
        with source_path.open(encoding="utf-8") as stream:
            config = self.yaml.load(stream)
        parameters = config.get("/**/speech_stack", {}).get("ros__parameters", {})
        for source in parameters.get("sources", []):
            if source.get("source_id") == "mic_0":
                source["enabled"] = answers.zoom_h8_enabled
            elif source.get("source_id") == "mic_1":
                source["enabled"] = answers.kinect_enabled
                source["capture_enabled"] = answers.kinect_transcription_enabled
                source["speech_enabled"] = answers.kinect_transcription_enabled
        path = self.local_dir / "haru_speech.yaml"
        with path.open("w", encoding="utf-8") as stream:
            self.yaml.dump(config, stream)
        for stack in ("speech", "all"):
            override_path = self.local_dir / f"compose-{stack}.yaml"
            if not override_path.exists():
                continue
            with override_path.open(encoding="utf-8") as stream:
                override = self.yaml.load(stream)
            speech_services = {
                "base",
                "audio",
                "audio-capture-manager",
                "recognition",
                "verification",
                "localization",
            }
            for name, service in override.get("services", {}).items():
                if name not in speech_services:
                    continue
                service.setdefault("volumes", []).append(
                    f"{path}:/shared/configs/haru_speech.yaml:ro"
                )
            with override_path.open("w", encoding="utf-8") as stream:
                self.yaml.dump(override, stream)

    def _write_secret(self, name: str, value: str) -> None:
        path = self.root / "envs" / "llm.secrets.env"
        existing = (
            {key: stored_value or "" for key, stored_value in dotenv_values(path).items()}
            if path.exists()
            else {}
        )
        existing[name] = value
        template_keys = (
            "LLM_SERVER_API_KEY",
            "OPENAI_API_KEY",
            "ANTHROPIC_API_KEY",
            "HF_TOKEN",
            "BEDROCK_API_KEY",
            "CUSTOM_LLM_API_KEY",
            "LANGFUSE_PUBLIC_KEY",
            "LANGFUSE_SECRET_KEY",
        )
        path.write_text("".join(f"{key}={existing.get(key, '')}\n" for key in template_keys), encoding="utf-8")
        path.chmod(stat.S_IRUSR | stat.S_IWUSR)

    def _write_custom_litellm(self, answers: SetupAnswers) -> None:
        source = self.root / "data" / "llm" / "configs" / "litellm_server.yaml"
        if not source.exists() or not answers.llm_api_base:
            return
        with source.open(encoding="utf-8") as stream:
            config = self.yaml.load(stream)
        config.setdefault("model_list", []).append(
            {
                "model_name": answers.llm_model_id,
                "litellm_params": {
                    "model": f"openai/{answers.llm_model_id}",
                    "api_base": answers.llm_api_base,
                    "api_key": "os.environ/CUSTOM_LLM_API_KEY",
                },
            }
        )
        destination = self.local_dir / "litellm_server.yaml"
        with destination.open("w", encoding="utf-8") as stream:
            self.yaml.dump(config, stream)
        for stack in ("llm", "all"):
            path = self.local_dir / f"compose-{stack}.yaml"
            if not path.exists():
                continue
            with path.open(encoding="utf-8") as stream:
                override = self.yaml.load(stream)
            server = override.get("services", {}).get("server")
            if server is not None:
                server.setdefault("volumes", []).append(f"{destination}:/app/config.yaml:ro")
            with path.open("w", encoding="utf-8") as stream:
                self.yaml.dump(override, stream)


def load_answers(root: Path) -> SetupAnswers:
    path = root / ".haru" / "answers.yaml"
    if not path.exists():
        raise FileNotFoundError("Run './setup.sh setup' first")
    yaml = YAML(typ="safe")
    with path.open(encoding="utf-8") as stream:
        return SetupAnswers.model_validate(yaml.load(stream))


def has_provider_secret(root: Path, answers: SetupAnswers) -> bool:
    path = root / "envs" / "llm.secrets.env"
    if not path.exists():
        return False
    return bool(dotenv_values(path).get(answers.secret_name))


def load_state(root: Path) -> dict[str, Any]:
    path = root / ".haru" / "state.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def save_state(root: Path, state: dict[str, Any]) -> None:
    path = root / ".haru" / "state.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(".tmp")
    temporary.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    os.replace(temporary, path)
